server:
  port: ${PORT:8081}

spring:
  application:
    name: ms-estudiantes

  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:estudiantesdb}}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
